name: Spell Check

on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install codespell
        run: pip install codespell

      - name: Run spell check
        run: codespell --skip=".git,*.pdf"
